language: python
sudo: false
services:
- mongodb
matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
before_install:
# INSTALL CONDA
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b -p /home/travis/mc"
- export PATH=/home/travis/mc/bin:$PATH
- conda config --set always_yes true
- conda update conda --yes
- conda config --add channels lightsource2
# DO SOME METADATASTORE SPECIFIC CONFIGURATION
- export MDS_HOST=localhost
- export MDS_DATABASE=test
- export MDS_TIMEZONE=US/Eastern
- mkdir -p /home/travis/.config/metadatastore
- 'echo ''port: 27017'' > /home/travis/.config/metadatastore/connection.yml'
# CONFIGURE USEFUL ENVIRONMENTAL VARIABLES
- export CONDA_BUILD_COMMAND="conda build conda-recipe --python=$TRAVIS_PYTHON_VERSION"
- export GIT_FULL_HASH=`git rev-parse HEAD`
- export CLEAN_ANACONDA_CHANNEL=false
# SOME DEBUG OUTPUT
- git describe
# INSTALL DEPS FOR BUILDING AND UPLOADING
- conda install conda-build jinja2 anaconda-client
# SET UP THE TEST ENVIRONMENT
- conda create -n testenv pip nose python=$TRAVIS_PYTHON_VERSION "pymongo=2.9" six pyyaml numpy pandas jinja2 mongoengine boltons prettytable humanize
- source activate testenv
- pip install coveralls codecov
- conda install -c ericdill depfinder
- pip install https://github.com/ericdill/conda-skeletor/zipball/master#egg=conda_skeletor
install:
- python setup.py install
# SOME DEBUG OUTPUT
- python -c "import metadatastore; print(metadatastore.__version__)"
script:
- python run_tests.py -v
# NEED TO GET (AT LEAST) THE COMMITS UP TO THE MOST RECENT TAG
- git fetch --unshallow
- "$CONDA_BUILD_COMMAND"
after_success:
# UPLOAD COVERAGE DATA
- coveralls
- codecov
- source deactivate
# CLEAN ANACONDA.ORG/LIGHTSOURCE2-DEV/METADATASTORE AND UPLOAD CONDA BINARY
# IF WE ARE ON THE MASTER BRANCH OF THE NSLS-II REPOSITORY AND THIS IS NOT A
# PULL REQUEST
- git clone https://github.com/ericdill/travis-little-helper
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    $CONDA_BUILD_COMMAND --output | bash travis-little-helper/anaconda-version-string.sh > version;
    anaconda login --username nsls2builder --password $ANACONDA_PASS --hostname "$TRAVIS_PYTHON_VERSION-`cat version`";
    bash travis-little-helper/clean-anaconda-channel.sh lightsource2-dev metadatastore $CLEAN_ANACONDA_CHANNEL;
    anaconda upload -u lightsource2-dev `$CONDA_BUILD_COMMAND --output`;
    anaconda logout;
  fi;
env:
  global:
    secure: "pYO9aM4keSwyVrom3/tbmjE0mwuSBKJ+SroIF56JUVLh8jT3jiHmwZfI3fUNY6erNewyoiFhkDDBvyY/gxXGHma6T0RcV+LAZmWCXePBL8fsm5X93lo3RlPFtqmXbkOW7C0+h4RDEMQP/UYsNJvL7YbmeDT+fNozV/CpK1zJtU4="
